database:
  # The type of used database
  # Supported types: [mysql, sqlite, postgresql]
  type: sqlite

  # MySQL connection configuration
  mysql:
    host: localhost
    port: 3306
    name: kinghill
    user: admin
    password: kinghill
    params:
    - 'autoReconnect=true'
    - 'useSSL=false'

  # PostgreSQL connection configuration
  postgresql:
    host: localhost
    port: 5432
    name: kinghill
    user: admin
    password: kinghill
    params:
    - 'autoReconnect=true'
    - 'useSSL=false'

  # SQLite connection configuration
  sqlite:
    file: database.db

# Количество игроков, которое должно быть в области царя горы, что бы игроку начислялись время.
players-required: 2
  # Для этой секции можно использовать плейслохлдеры времени:
  # ss - секунды
  # mm - минуты
  # hh - часы
  # dd - дни
placeholder-time-pattern: "mm:ss"

# Время в секундах, которое необходимо простоять, что бы получить награду
daily-reward-required: 60

# Таймер в секундах для обновления плейсхолдеров для HolographicDisplays 
holographic-displays-update-time: 1

# Тут выдаётся награда путём использования команд от имени консоли.
# Пишете сюда команды, что бы выдать игроку награду.
# Что бы указать имя игрока используйте плейсхолдер %player%
reward:
  - "say hello %player%"

# Если у плейсхолдера нет данных, то он будет выводить это:
no-data: "---"