name: ${project.name}
main: ru.starmc.kinghill.KingHill
version: ${project.version}
author: Mrflaxe
depend: [SKLibrary]
softdepend: [PlaceholderAPI, HolographicDisplays]
api-version: 1.15

commands:
  kinghill:
    aliases: [kh]
    usage: /kinghill
    default: op
  cancel:
    usage: /cancel
    default: op

permissions:
  kinghill.command.create:
    description: allows to create new kinghills
    default: op
  kinghil.command.cancel:
    description: cancelling kinghill creation
    default: op
  kinghill.command.reload:
    description: reloads configurations
    default: op