name: ${project.name}
main: ru.starmc.kinghill.KingHill
version: ${project.version}
author: Mrflaxe
depend: [SKLibrary]
softdepend: [PlaceholderAPI]
api-version: 1.15

commands:
  kinghill:
    aliases: [kh]
    usage: /kinghill
    default: op

permissions:
  kinghill.command.create:
    description: allows to create new kinghills
    default: op
